get rid of template commands and templates

diff --git a/commands/sdcli_go_dep b/commands/sdcli_go_dep
--- a/commands/sdcli_go_dep
+++ b/commands/sdcli_go_dep
@@ -10,5 +10,6 @@ if test -f "go.mod"; then
     export GO111MODULE=on
     go mod vendor
 else
-    dep ensure -v
+    echo "go.mod not found, giving up" 1>&2
+    exit 1
 fi
